version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:30"
  reviewers:
  - gilbertly
  labels:
  - dependabot
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.831.0
    - 2.834.0
    - 2.879.0
  - dependency-name: dot-prop
    versions:
    - 5.3.0
  - dependency-name: "@sentry/node"
    versions:
    - 6.0.1
    - 6.0.3
  - dependency-name: ini
    versions:
    - 1.3.8
