service:
  name: starter-appsync

plugins:
  - serverless-webpack
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

custom:
  webpack:
    webpackConfig: ./config/webpack.config.js
    packagePath: ./package.json
    packager: npm
    forceExclude:
      - aws-sdk
  appSync:
    name: ${self:service.name}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    schema: ./aws/xyz.gilbertly.api/schema.private.graphql
    mappingTemplatesLocation: ./aws/xyz.gilbertly.api/templates
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: '#{CognitoUserPool}'
    dataSources:
      - ${file(./aws/xyz.gilbertly.api/appsync.datasources.yml)}
    mappingTemplates:
      - ${file(./aws/xyz.gilbertly.api/appsync.resolvers.yml)}
  ssmPath:
    sentry_dsn: ${ssm:/aws_appsync/sls/sentry_dsn}
    xyz_gilbertly_api_domain: ${ssm:/aws_appsync/sls/xyz_gilbertly_api_domain}

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 10 # seconds
  memorySize: 512
  stage: ${opt:region, 'dev'}
  region: ${opt:region, 'us-east-1'}
  logRetentionInDays: 7
  stackName: ${self:provider.stage}-${self:service.name}
  profile: deployuser-${self:provider.stage}
  tags:
    project: ${self:provider.stage}-${self:service.name}
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  environment:
    SENTRY_DSN: ${self:custom.ssmPath.sentry_dsn}

layers:
  dependencies:
    name: appsync_starter
    description: Appsync lambda dependencies.
    package:
      artifact: dependencies.zip
    compatibleRuntimes:
      - nodejs10.x
    licenseInfo: MIT

package:
  exclude:
    - .git/**
    - .serverless/**
    - node_modules/**
    - coverage/**
    - src/__tests__/**
    - aws/**
  include:
    - src/**
  excludeDevDependencies: true

functions:
  getHelloQueryFn:
    name: getHelloQueryFn
    handler: src/functions/getHelloQueryFn.handler
    description: Resolve Appsync <> DynamoDB operations.
    layers:
      - !Ref DependenciesLambdaLayer

resources:
  - ${file(./aws/iam.users.roles.kms.yml)}
  - ${file(./aws/xyz.gilbertly.api/cognito.user.pool.yml)}
  - ${file(./aws/xyz.gilbertly.api/cognito.identity.pool.yml)}
  - ${file(./aws/xyz.gilbertly.api/cloudfront.route53.yml)}
