service:
  name: starter-appsync

plugins:
  - serverless-webpack
  - serverless-appsync-plugin
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

custom:
  webpack:
    webpackConfig: ./config/webpack.config.js
    packagePath: ./package.json
    packager: npm
    forceExclude:
      - aws-sdk
  appSync:
    name: ${self:provider.stage}-${self:service.name}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    schema: ./aws/schema.graphql
    mappingTemplatesLocation: ./aws/templates
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: !Ref CognitoUserPool
    dataSources:
      - ${file(./aws/appsync_datasources.yml)}
    mappingTemplates:
      - ${file(./aws/appsync_resolvers.yml)}
  serverless-iam-roles-per-function:
    defaultInherit: true
  ssmPath:
    sentry_dsn: ${ssm:/starter_appsync/sentry_dsn, ''}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10 # seconds
  memorySize: 512
  stage: ${opt:region, 'dev'}
  region: ${opt:region, 'us-east-1'}
  logRetentionInDays: 7
  stackName: ${self:provider.stage}-${self:service.name}
  profile: deployuser-${self:provider.stage}
  tags:
    project: ${self:provider.stage}-${self:service.name}
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  environment:
    SENTRY_DSN: ${self:custom.ssmPath.sentry_dsn}

layers:
  dependencies:
    name: ${self:provider.stage}-${self:service.name}
    description: Appsync lambda dependencies.
    package:
      artifact: dependencies.zip
    compatibleRuntimes:
      - nodejs12.x
    licenseInfo: MIT

package:
  exclude:
    - .git/**
    - .serverless/**
    - node_modules/**
    - coverage/**
    - src/__tests__/**
    - aws/**
  include:
    - src/**
  excludeDevDependencies: true

functions:
  getHelloQueryFn:
    name: getHelloQueryFn
    handler: src/functions/getHelloQueryFn.handler
    description: Sample appsync query.
    layers:
      - !Ref DependenciesLambdaLayer

  addHelloMutationFn:
    name: addHelloMutationFn
    handler: src/functions/addHelloMutationFn.handler
    description: Sample appsync mutation.
    layers:
      - !Ref DependenciesLambdaLayer

  postConfirmFn:
    name: postConfirmFn
    handler: src/functions/postConfirmFn.handler
    description: Triggers after a user confirms their email.
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminAddUserToGroup
          - cognito-idp:AdminRemoveUserFromGroup
        Resource: '*'
    layers:
      - !Ref DependenciesLambdaLayer

resources:
  - ${file(./aws/iam_permissions.yml)}
  - ${file(./aws/dynamodb_tables.yml)}
  - ${file(./aws/cognito_userpool.yml)}
  - ${file(./aws/cognito_identitypool.yml)}
  - ${file(./aws/stream_analytics.yml)}
