Resources:
  AcmCertificateXyzGilbertly:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: ${self:custom.ssmPath.xyz_gilbertly_wildcard}
      ValidationMethod: DNS

  Route53HostedZoneXyzGilbertly:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: ${self:custom.ssmPath.xyz_gilbertly_domain}
      HostedZoneConfig:
        Comment: ${self:custom.ssmPath.xyz_gilbertly_domain}

  Route53RecordSetGroupXyzGilbertly:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: ${self:custom.ssmPath.xyz_gilbertly_domain} subdomains.
      HostedZoneId: '#{Route53HostedZoneXyzGilbertly}'
      RecordSets:
        # https://gilbertly.xyz
        - Name: ${self:custom.ssmPath.xyz_gilbertly_domain}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's Magic Number
            DNSName: '#{CloudFrontDistributionXyzGilbertlyApi.DomainName}'

        # https://api-dev.gilbertly.xyz
        - Name: ${self:custom.ssmPath.xyz_gilbertly_api_domain}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's Magic Number
            DNSName: '#{CloudFrontDistributionXyzGilbertlyApi.DomainName}'

Outputs:
  Route53HostedZoneXyzGilbertlyId:
    Description: Hosted zone id for ${self:custom.ssmPath.xyz_gilbertly_domain}.
    Value: '#{Route53HostedZoneXyzGilbertly}'
    Export:
      Name: HostedZoneId-XyzGilbertly
