version: 2.1
refs:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: ~/app

  steps:
    - &install_dependencies
      run:
        name: Install Dependencies
        command: |
          npm install
          sudo apt-get -y -qq install awscli
    - &save_cache
      save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - &restore_cache
      restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
    - &persist_workspace
      persist_to_workspace:
        root: ./
        paths:
          - ./
    - &attach_workspace
      attach_workspace:
        at: ~/app
    - &test_build
      run:
        name: Run Tests, Audit Fix, & Build
        command: npm run validate:all
    - &sentry_release
      run:
        name: Sentry Release
        command: |
          export SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
          export SENTRY_ORG=${SENTRY_ORG}
          VERSION=$(git rev-parse --short HEAD)
          ./node_modules/.bin/sentry-cli releases new -p ${SENTRY_PROJECT} $VERSION
          ./node_modules/.bin/sentry-cli releases set-commits --auto $VERSION
    - &semantic_release
      run:
        name: Semantic Release
        command: |
          export NPM_TOKEN=${NPM_TOKEN}
          export GH_TOKEN=${GH_TOKEN}
          export GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
          export GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
          export GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME}
          export GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL}
          npx semantic-release
    - &upload_coverage
      run:
        name: Upload Tests' Coverage
        codecov/upload:
          conf: ./codecov.yml
          token: ${CODECOV_TOKEN}
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - *install_dependencies
      - *save_cache
      - *restore_cache
      - *test_build
      - *persist_workspace

  deploy_dev:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Integration test:Dev
          command: npm run newman:dev
      - run:
          name: Configure Serverless AWS Dev Credentials
          command: |
            ./node_modules/.bin/sls config credentials \
            --provider aws \
            --key ${ACCESS_KEY} \
            --secret ${SECRET_KEY} \
            --profile deployuser-dev
      - run:
          name: Deploy Dev
          command: npm run deploy:dev

  deploy_prod:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Integration test:Prod
          command: npm run newman:prod
      - run:
          name: Configure Serverless AWS Prod Credentials
          command: |
            ./node_modules/.bin/sls config credentials \
            --provider aws \
            --key ${ACCESS_KEY} \
            --secret ${SECRET_KEY} \
            --profile deployuser-prod
      - run:
          name: Deploy Prod
          command: npm run deploy:prod

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy_dev:
          context: sls-starter-appsync-dev
          filters:
            branches:
              only:
                - develop
          requires:
            - build
      - deploy_prod:
          context: sls-starter-appsync-prod
          filters:
            branches:
              only:
                - master
          requires:
            - build
