Resources:
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: ${self:service.name}-identitypool
      AllowUnauthenticatedIdentities: false
      # SupportedLoginProviders:
      #   accounts.google.com: ${self:custom.ssmPath.google_oauth_url}
      #   api.twitter.com: ${self:custom.ssmPath.twitter_oauth_url}
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName

  CognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthRole.Arn

Outputs:
  IdentityPoolId:
    Description: ${self:service.name} identity pool id.
    Value: !Ref CognitoIdentityPool
