Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service.name}-userpool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service.name}-userpool-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      CallbackURLs: # authenticated landing page
        - https://app.gilbertly.xyz
      LogoutURLs: # un-authenticated landing page
        - https://gilbertly.xyz

Outputs:
  UserPoolId:
    Description: ${self:service.name} userpool id.
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Description: ${self:service.name} userpool client id.
    Value: !Ref CognitoUserPoolClient
