Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service.name}-userpool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 6 #characters
      LambdaConfig:
        PostConfirmation: !GetAtt PostConfirmFnLambdaFunction.Arn

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: ${self:service.name}

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service.name}-userpool-client
      UserPoolId: !Ref CognitoUserPool
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlowsUserPoolClient: true
      RefreshTokenValidity: 14 #days
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      AnalyticsConfiguration:
        ApplicationId: !Ref PinpointAppAnalytics
        ExternalId: !GetAtt CognitoPinpointAnalyticsRole.RoleId
        RoleArn: !GetAtt CognitoPinpointAnalyticsRole.Arn
        UserDataShared: true
      SupportedIdentityProviders:
        - COGNITO
        - Google
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlows:
        - implicit
      CallbackURLs:
        - https://localhost:8000/
        - https://app.gilbertly.xyz/
      LogoutURLs:
        - https://localhost:8000/auth
        - https://app.gilbertly.xyz/auth

  CognitoUserGroupBasic:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: BASIC
      UserPoolId: !Ref CognitoUserPool
      Description: Basic/free access to backend resources.
      Precedence: 30

  CognitoUserGroupStarter:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: STARTER
      UserPoolId: !Ref CognitoUserPool
      Description: Starter paid access to backend resources.
      Precedence: 20

  CognitoUserGroupPremium:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: PREMIUM
      UserPoolId: !Ref CognitoUserPool
      Description: Premium paid access to backend resources.
      Precedence: 10

Outputs:
  UserPoolId:
    Description: ${self:service.name} userpool id.
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Description: ${self:service.name} userpool client id.
    Value: !Ref CognitoUserPoolClient
