Resources:
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: ${self:service.name}-identitypool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName

  CognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthRole.Arn

  CognitoIdentityPoolGoogle:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderName: Google
      ProviderType: Google
      UserPoolId: !Ref CognitoUserPool
      AttributeMapping:
        email: email
      ProviderDetails:
        client_id: ${self:custom.ssmPath.google_client_id}
        client_secret: ${self:custom.ssmPath.google_client_secret}
        authorize_scopes: email openid profile

Outputs:
  IdentityPoolId:
    Description: ${self:service.name} identity pool id.
    Value: !Ref CognitoIdentityPool
