Resources:
  SQSMutationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:provider.stage}-appsync-mutations
      MessageRetentionPeriod: 604800 # 7 days

  ItemsDynamodbTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:provider.stage}-${self:service.name}-items
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: itemID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: itemID
          AttributeType: S
