Resources:
  ItemsDynamodbTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    # DeletionPolicy: Retain
    Properties:
      TableName: ${self:provider.stage}-${self:service}
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: True
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: items-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
