Resources:
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:service.name}-cognito-auth-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: CognitoAuthorizedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                  - cognito-sync:*
                  - cognito-identity:*
                Resource: '*'
              - Effect: Allow
                Action: execute-api:Invoke
                Resource: '*'

  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:service.name}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:*'

  CognitoPinpointAnalyticsRole:
    Type: AWS::IAM::Role
    DependsOn: PinpointAppAnalytics
    Properties:
      Path: /
      RoleName: ${self:service.name}-pinpoint-cognito-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CollectCognitoAnalytics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                Resource: !GetAtt PinpointAppAnalytics.Arn

  CognitoPostConfirmTriggerPermission:
    Type: AWS::Lambda::Permission
    DependsOn: CognitoUserPool
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PostConfirmFnLambdaFunction.Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt CognitoUserPool.Arn
