version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: weekly
    default_reviewers:
      - gilbertly
    default_labels:
      - dependabot
    allowed_updates:
      - match: # open PR prod updates
          dependency_type: 'production'
          update_type: 'all'
      - match: # open PR all security
          dependency_type: 'all'
          update_type: 'security'
    automerged_updates:
      - match: # automerge prod minor updates (1.0.x - 1.2.x)
          dependency_type: 'production'
          update_type: 'semver:minor'
      - match: # automerge all security patch updates
          dependency_type: 'all'
          update_type: 'security:patch'
    version_requirement_updates: auto
