Resources:
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: ${self:provider.stage}IdentityPool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: '#{CognitoUserPoolClient}'
          ProviderName: '#{CognitoUserPool.ProviderName}'

  CognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: '#{CognitoIdentityPool}'
      Roles:
        authenticated: '#{CognitoAuthRole.Arn}'
        unauthenticated: '#{CognitoUnauthRole.Arn}'

Outputs:
  IdentityPoolId:
    Value: '#{CognitoIdentityPool}'
